# Generated by Django 4.0.4 on 2022-05-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_prodctimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdctImage',
            new_name='ProductImage',
        ),
    ]
