# Generated by Django 4.0.4 on 2022-05-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
